# Generated by Django 5.2.16 on 2026-07-07 17:45

import django.db.models.deletion
import missions.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default=missions.domain.enums.MissionStatus['DRAFT'], max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('required_volunteers', models.PositiveIntegerField(default=1)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_missions', to=settings.AUTH_USER_MODEL)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='disasters.disaster')),
            ],
            options={
                'db_table': 'missions_mission',
                'ordering': ['-created_at'],
            },
        ),
    ]
