# Generated by Django 5.2.16 on 2026-07-09 14:33

import django.db.models.deletion
import missions.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('skills', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='allow_volunteer_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='equipment_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_visible_to_volunteers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mission',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default=missions.domain.enums.MissionPriority['MEDIUM'], max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='safety_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='special_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default=missions.domain.enums.MissionApplicationStatus['SUBMITTED'], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='missions.mission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mission_applications', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_applications', to='volunteers.volunteerprofile')),
            ],
            options={
                'db_table': 'missions_mission_application',
                'ordering': ['-created_at'],
                'unique_together': {('mission', 'volunteer')},
            },
        ),
        migrations.CreateModel(
            name='MissionRequiredSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='missions.mission')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_requirements', to='skills.skill')),
            ],
            options={
                'db_table': 'missions_mission_required_skill',
                'ordering': ['skill__category', 'skill__name'],
                'unique_together': {('mission', 'skill')},
            },
        ),
    ]
