# Generated by Django 5.2.16 on 2026-07-07 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'skills_skill',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('proficiency', models.PositiveSmallIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_skills', to='skills.skill')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_skills', to='volunteers.volunteerprofile')),
            ],
            options={
                'db_table': 'skills_volunteer_skill',
                'ordering': ['-created_at'],
                'unique_together': {('volunteer', 'skill')},
            },
        ),
    ]
