# Generated by Django 5.2.16 on 2026-07-07 17:45

import django.db.models.deletion
import uuid
import volunteers.domain.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('national_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected')], db_index=True, default=volunteers.domain.enums.VolunteerStatus['PENDING_APPROVAL'], max_length=30)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteers_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
