# Generated by Django 5.2.16 on 2026-07-07 17:45

import assignments.domain.enums
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('checked_in', 'Checked In'), ('completed', 'Completed')], db_index=True, default=assignments.domain.enums.AssignmentStatus['PENDING'], max_length=20)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='missions.mission')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteers.volunteerprofile')),
            ],
            options={
                'db_table': 'assignments_assignment',
                'ordering': ['-created_at'],
                'unique_together': {('mission', 'volunteer')},
            },
        ),
    ]
