flowchart TB
  U[Actors] --> P0[Panah Process]
  P0 --> D1[(Operational DB)]
  P0 --> D2[(Cache Redis)]
  P0 --> E1[Email Channel]
  subgraph L1
    P1[Identity & Access]
    P2[Crisis & Mission Mgmt]
    P3[Volunteer Matching]
    P4[Reporting & Support]
  end
  U --> P1 & P2 & P3 & P4
  P1 --> D1
  P2 --> D1
  P3 --> D1
  P4 --> D1
  P1 --> D2
  P4 --> E1
